### ISSUE TITLE
README provides Maven instructions instead of Gradle

### ISSUE THREAD

**Issue by jmmk** [andrewoma/dexx#1]
`* Dexx is currently built with maven. Use `mvn install` to build and install into your local repository.`
should become
`* Dexx is currently built with gradle. Use `./gradlew install` to build and install into your local repository.`

Not sure what should become of this block:

```
* By default, a quick version of tests are run. Getting better test coverage of `Vectors` requires large
  collections. To run tests with complete coverage use: `mvn -Ddexx.test.mode=COMPLETE -P cobertura clean cobertura:cobertura`
* To run the benchmarks, use `mvn -Ddexx.test.mode=BENCHMARK test` (results are lines starting with BENCHMARK).
```

**Comment by andrewoma** [comment]
Thanks for pointing that out - I clearly missed them when converting the project over. I've now updated the README and build to allow benchmarking and coverage via gradle.

Thanks again.
