### ISSUE TITLE
Add method count for Android developers

### ISSUE THREAD

**Issue by vaughandroid** [andrewoma/dexx#10]
Android has a 64k method limit, so a lot of Android developers take method count into consideration when choosing libraries. 

As this library appears to be pretty compact (especially compared to some of the bloat-ridden alternatives like Guava) highlighting the method count might encourage more use by Android developers.

**Comment by andrewoma** [comment]
Hi Chris, I'm happy to add the number to the readme if you calculate it. I don't have the android tool chain handy to generate a dex file to get an official count.

**Comment by vaughandroid** [comment]
Here's the results I get:

**Comment by vaughandroid** [comment]
Here's the results I get from the [dexcount plugin](https://github.com/KeepSafe/dexcount-gradle-plugin):
- 'com.github.andrewoma.dexx:collection:0.6' = 1036 methods
- 'com.github.andrewoma.dexx:kollection:0.6' = 1213 methods

**Comment by andrewoma** [comment]
Thanks, I've added the counts to the README
