### ISSUE TITLE
Documentation request

### ISSUE THREAD

**Issue by greyson** [andrewoma/dexx#12]
Is there anyway to add benchmarks of what Dexx's performance is compared to Java acting in the same way?  I've been using the `java.util` collections in an immutable fashion for a while, and the most telling benchmark in there for immutable use of the java collections is prepending elements to a list.

Also, a side note, it may be nice to have Sets.collector(), Lists.collector() etc to work with Java 1.8's collection streaming interface; I've done a couple of trivial ones that I might be able to make a pull request for when I finish with the project I'm currently working on (scheduled for delivery mid-to-late March).

**Comment by ptitjes** [comment]
@greyson I did some [benchmarks](https://github.com/ptitjes/benchmark-immutables/blob/master/results/2016-10-02-23:56:36.pdf) one year ago. You run them again by checking out my [repository](https://github.com/ptitjes/benchmark-immutables).

**Comment by andrewoma** [comment]
FYI, I added a link to @ptitjes benchmarks. I also like the collectors idea
