### ISSUE TITLE
Set< A > Does not use .equals as comments contend.

### ISSUE THREAD

**Issue by greyson** [andrewoma/dexx#13]
I had an object consisting of three scalar values the `.equals()` method used the `equals()` method on these for comparison.  

The set continued to contain duplicates.  Implementing `hashCode()` with respect to the scalar values was the only solution.

**Comment by jcornaz** [comment]
>The set continued to contain duplicates. Implementing hashCode() with respect to the scalar values was the only solution.

This is expected and you would experience the same with `HashSet` and `HashMap` of the Java standard library.  `hashcode` should **always** returns the same value for two instances which are "equals".

* https://docs.oracle.com/javase/10/docs/api/java/lang/Object.html#equals(java.lang.Object)
* https://docs.oracle.com/javase/10/docs/api/java/lang/Object.html#hashCode()

**Comment by greyson** [comment]
I'm more referring to the comment at the top of the Set class (possibly subclasses, but it's been a while since I've looked through the code) 

    /**
     * Set defines the interface for a unique set of values as defined by {@link java.lang.Object#equals(Object)}.
     */

For someone investigating the code (or the docs in the future) this would be misleading... as it was for me, at least.

**Comment by andrewoma** [comment]
Sorry, I didn't actually understand your issue when you created it.  But in a nutshell you always have to override `hashCode` when overriding `equals` on the JVM. Some tooling will even warn you if you break the implicit contract (and `java.util.HashSet` and `java.util.HashMap` will fail).

Within the documentation of `Object.equals` it also warns you:
```
* Note that it is generally necessary to override the {@code hashCode}
     * method whenever this method is overridden, so as to maintain the
     * general contract for the {@code hashCode} method, which states
     * that equal objects must have equal hash codes.
```

**Comment by greyson** [comment]
I understand your point, now.  I think the confusion comes in since we are typically only dealing with `Set` and `Sets` here, whereas in standard java, the implementation is necessarily clear because the implementation you instantiate dictates how the set is organized; e.g. Using `new HashSet<>()` is clearly going to create a set of objects relying on `hashCode()`; but using `Sets.of()` only returns the interface-level `Set<>`.  

I see the documentation of `Sets` noting that all sets returned are hash sets, maybe it would be proper to move `Sets.of()` to `HashSets.of()` -- but that does detract from the brevity.

**Comment by jcornaz** [comment]
@greyson overriding `equals` without overriding `hashCode` is always wrong. Even if `hashCode` is not called. This is a contract that any object in Java should fulfill, and any function/library should always be able to safely assume that this contract is fulfilled.

That's why any IDE will always propose you to generate both `equals` and `hashCode` at the same time.

This is also why in Kotlin we don't even have to bother because the modifier `data` make the compiler generate *both* `equals` and `hashCode`.
