### ISSUE TITLE
New release to Maven Central?

### ISSUE THREAD

**Issue by ajs6f** [andrewoma/dexx#5]
The version of Dexx Collections available from Maven Central is 0.2, but it seems that there have been several moves ahead since 2014 (when that Maven Central release was made). Is it possible to please have a more recent release supplied? Thanks!

**Comment by andrewoma** [comment]
Hi, there are more recent releases in maven central (0.5) - however, the artifact name has changed (when moving to gradle and introducing a kotlin variant).

See: http://search.maven.org/#artifactdetails%7Ccom.github.andrewoma.dexx%7Ccollection%7C0.5%7Cjar
and
http://search.maven.org/#artifactdetails%7Ccom.github.andrewoma.dexx%7Ckollection%7C0.5%7Cjar

**Comment by ajs6f** [comment]
Ah, cool-- thanks!
