### ISSUE TITLE
OSGi metadata?

### ISSUE THREAD

**Issue by ajs6f** [andrewoma/dexx#6]
It would be useful for the Dexx artifacts to include OSGi metadata, and the cost is very low. I include a PR that does the job for the Java artifact. Thanks!

**Comment by andrewoma** [comment]
I've merged the pull request. If you confirm it does what you need (I don't have any way to test it myself) then I can push out a new release to maven central for you

**Comment by ajs6f** [comment]
Thanks very much-- I will get on the work of confirming that and come back to you pronto!

**Comment by ajs6f** [comment]
We've confirmed that the new metadata does well what we need. Please do push a release, and let me know if I can help in any way. (Unlikely, but I thought I'd offer.)

**Comment by andrewoma** [comment]
0.6 has been released and available in maven central: https://repo1.maven.org/maven2/com/github/andrewoma/dexx/collection/0.6/

Enjoy!
